name: Generate Podcast Feeds
on: [push]
permissions:
  contents: write
  pull-requests: write
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
      - name: Run Feed Generator
        uses: malexanderlvz/podcast-generator@main

